### ISSUE TITLE
Can you share with us the `.obj` models you used in the scene? 

### ISSUE THREAD

**Issue by ivanceras** [Twinklebear/tray_rust#1]
Can you share with us the `.obj` models you used in the scene? 
I downloaded the bunny.obj in standford repo and used in the scense examples but it gives me errors like
`Normals and texture coordinates are required!`

**Comment by Twinklebear** [comment]
Yea, I've been meaning to put together an assets bundle with the models since some have slight modifications (generated normals, uv coordinates). I'll look into this tomorrow, all I really need to add are some attribution links for where they're from. I'll close this when I post a link to the assets

**Comment by Twinklebear** [comment]
I've put together a models bundle which you can get [here](https://drive.google.com/file/d/0B-l_lLEMo1YecFdtRlM5WEY3eE0/view?usp=sharing), there's also a link to this zip in the readme now.

**Comment by ivanceras** [comment]
@Twinklebear, thank you for sharing the models and this awesome project as well. 
One more thing, can you share the `brdfs` as well. I got these errors when trying out with the more complex scenes

``` rust
thread '<main>' panicked at 'material::Merl::load_file - failed to open "./scenes/brdfs/black-oxidized-steel.binary" due to No such file or directory (os error 2)', src/material/merl.rs:46
```

**Comment by Twinklebear** [comment]
Since the BRDFs don't need any modification it's easier to just link to the [MERL BRDF Database](http://www.merl.com/brdf/) where they can be downloaded, a link is also in the model bundle's readme. The names of the files are the same as those in the database, so they can all be found on the author's site [here](http://people.csail.mit.edu/wojciech/BRDFDatabase/brdfs/) (linked from the database).
