### ISSUE TITLE
Cornell box result is fuzzy

### ISSUE THREAD

**Issue by tyler274** [Twinklebear/tray_rust#7]
![frame00000](https://user-images.githubusercontent.com/4147075/66445762-eb099f80-ea15-11e9-8e16-6417ff605936.png)

Built off the latest master.

**Comment by Twinklebear** [comment]
This is the expected result for the JSON file in the repo, since I set a very low sample count so it would render quickly. To render a less noisy image you can increase the [sample count](https://github.com/Twinklebear/tray_rust/blob/master/scenes/cornell_box.json#L5) to something like 256 or higher, though it will take longer to render. With a higher sample count you'll get a nicer image, for example this is what you should get with 1024 samples per-pixel:

![image](https://user-images.githubusercontent.com/1522476/66446376-88a9a280-ea07-11e9-914b-87d93acd8a86.png)

**Comment by Twinklebear** [comment]
Oh I should also mention, the sample count needs to be a power of 2

**Comment by tyler274** [comment]
Thanks for the quick reply on how that's supposed to work
